//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentTheBike.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bicycle
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string TypeName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> RentPrice { get; set; }
    }
}
